<a href="https://colab.research.google.com/github/ninjaabhinav/classical-ml-projects/blob/main/Sentiment_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [67]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [68]:
df = pd.read_csv('7817_1.csv')
df.head()

,id,asins,brand,categories,colors,dateAdded,dateUpdated,dimension,ean,keys,...,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.userCity,reviews.userProvince,reviews.username,sizes,upc,weight
0,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I initially had trouble deciding between the p...,"Paperwhite voyage, no regrets!",NaN,NaN,Cristina M,NaN,NaN,205 grams
1,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,Allow me to preface this with a little history...,One Simply Could Not Ask For More,NaN,NaN,Ricky,NaN,NaN,205 grams
2,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,4.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I am enjoying it so far. Great for reading. Ha...,Great for those that just want an e-reader,NaN,NaN,Tedd Gardiner,NaN,NaN,205 grams
3,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I bought one of the first Paperwhites and have...,Love / Hate relationship,NaN,NaN,Dougal,NaN,NaN,205 grams
4,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I have to say upfront - I don't like coroporat...,I LOVE IT,NaN,NaN,Miljan David Tanic,NaN,NaN,205 grams

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1597 entries, 0 to 1596
Data columns (total 27 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    1597 non-null   object
 1   asins                 1597 non-null   object
 2   brand                 1597 non-null   object
 3   categories            1597 non-null   object
 4   colors                774 non-null    object
 5   dateAdded             1597 non-null   object
 6   dateUpdated           1597 non-null   object
 7   dimension             565 non-null    object
 8   ean                   898 non-null    float64
 9   keys                  1597 non-null   object
 10  manufacturer          965 non-null    object
 11  manufacturerNumber    902 non-null    object
 12  name                  1597 non-null   object
 13  prices                1597 non-null   object
 14  reviews.date          1217 non-null   object
 15  reviews.doRecommend   539 non-null    object
 16  reviews.numHelpful    900 non-null    float64
 17  reviews.rating        1177 non-null   float64
 18  reviews.sourceURLs    1597 non-null   object
 19  reviews.text          1597 non-null   object
 20  reviews.title         1580 non-null   object
 21  reviews.userCity      0 non-null      float64
 22  reviews.userProvince  0 non-null      float64
 23  reviews.username      1580 non-null   object
 24  sizes                 0 non-null      float64
 25  upc                   898 non-null    float64
 26  weight                686 non-null    object
dtypes: float64(7), object(20)
memory usage: 337.0+ KB

In [70]:
df.isnull().sum()

id                         0
asins                      0
brand                      0
categories                 0
colors                   823
dateAdded                  0
dateUpdated                0
dimension               1032
ean                      699
keys                       0
manufacturer             632
manufacturerNumber       695
name                       0
prices                     0
reviews.date             380
reviews.doRecommend     1058
reviews.numHelpful       697
reviews.rating           420
reviews.sourceURLs         0
reviews.text               0
reviews.title             17
reviews.userCity        1597
reviews.userProvince    1597
reviews.username          17
sizes                   1597
upc                      699
weight                   911
dtype: int64

In [71]:
len(df)

1597

In [72]:
df.drop(columns=[
    'reviews.userCity',
    'reviews.userProvince',
    'sizes',
    'dimension',
    'ean',
    'manufacturerNumber'
], inplace=True)

In [73]:
df['weight'] = df['weight'].str.extract('(\d+\.?\d*)')
df['weight'] = pd.to_numeric(df['weight'], errors='coerce')

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipython-input-268869747.py:1: SyntaxWarning: invalid escape sequence '\d'
  df['weight'] = df['weight'].str.extract('(\d+\.?\d*)')

In [74]:
df['weight'].fillna(df['weight'].median(), inplace=True)

/tmp/ipython-input-3362686935.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['weight'].fillna(df['weight'].median(), inplace=True)

In [75]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['brand'] = le.fit_transform(df['brand'])

In [76]:
print(df.columns)

Index(['id', 'asins', 'brand', 'categories', 'colors', 'dateAdded',
       'dateUpdated', 'keys', 'manufacturer', 'name', 'prices', 'reviews.date',
       'reviews.doRecommend', 'reviews.numHelpful', 'reviews.rating',
       'reviews.sourceURLs', 'reviews.text', 'reviews.title',
       'reviews.username', 'upc', 'weight'],
      dtype='object')

In [77]:
df[['prices', 'weight', 'brand']].dtypes

prices     object
weight    float64
brand       int64
dtype: object

In [78]:
df['prices'].head()

0    [{"amountMax":139.99,"amountMin":139.99,"curre...
1    [{"amountMax":139.99,"amountMin":139.99,"curre...
2    [{"amountMax":139.99,"amountMin":139.99,"curre...
3    [{"amountMax":139.99,"amountMin":139.99,"curre...
4    [{"amountMax":139.99,"amountMin":139.99,"curre...
Name: prices, dtype: object

In [79]:
import ast

def extract_price(x):
    try:
        data = ast.literal_eval(x)
        return data[0]['amountMin']
    except:
        return None

df['prices'] = df['prices'].apply(extract_price)

In [80]:
df['prices'] = pd.to_numeric(df['prices'], errors='coerce')
df['prices'] = df['prices'].fillna(df['prices'].median())

In [81]:
df[['prices', 'weight', 'brand']].dtypes

prices    float64
weight    float64
brand       int64
dtype: object

In [82]:
df_model = df[['prices', 'weight', 'brand', 'reviews.doRecommend']]

df_model = df_model.dropna(subset=['reviews.doRecommend'])
df_model['reviews.doRecommend'] = df_model['reviews.doRecommend'].astype(int)

In [83]:
df_sentiment = df[['reviews.text', 'reviews.doRecommend']].dropna()

df_sentiment['reviews.doRecommend'] = df_sentiment['reviews.doRecommend'].astype(int)

In [84]:
from sklearn.model_selection import train_test_split

X = df_sentiment['reviews.text']
y = df_sentiment['reviews.doRecommend']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [85]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words='english')

X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

In [86]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_tfidf, y_train)

MultinomialNB()

In [87]:
from sklearn.metrics import accuracy_score, confusion_matrix

y_pred = model.predict(X_test_tfidf)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.9629629629629629
Confusion Matrix:
 [[  0   4]
 [  0 104]]